name: Build Registry

on:
  push:

jobs:
  build-satis:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, intl, pdo_sqlite
        coverage: none

    - name: Composer install
      run: |
        composer install --no-interaction

    - name: Build satis
      run: |
        ssh -T git@github.com 2>&1 | tee /dev/null
        vendor/bin/satis build --no-interaction --skip-errors
